In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_csv('/Users/mac/Documents/Chat-Bot-Telegram/DataSet/Amazon/amazon_products.csv')
df.head(20)

,asin,title,imgUrl,productURL,stars,reviews,price,listPrice,category_id,isBestSeller,boughtInLastMonth
0,B014TMV5YE,"Sion Softside Expandable Roller Luggage, Black...",https://m.media-amazon.com/images/I/815dLQKYIY...,https://www.amazon.com/dp/B014TMV5YE,4.5,0,139.99,0.00,104,False,2000
1,B07GDLCQXV,Luggage Sets Expandable PC+ABS Durable Suitcas...,https://m.media-amazon.com/images/I/81bQlm7vf6...,https://www.amazon.com/dp/B07GDLCQXV,4.5,0,169.99,209.99,104,False,1000
2,B07XSCCZYG,Platinum Elite Softside Expandable Checked Lug...,https://m.media-amazon.com/images/I/71EA35zvJB...,https://www.amazon.com/dp/B07XSCCZYG,4.6,0,365.49,429.99,104,False,300
3,B08MVFKGJM,Freeform Hardside Expandable with Double Spinn...,https://m.media-amazon.com/images/I/91k6NYLQyI...,https://www.amazon.com/dp/B08MVFKGJM,4.6,0,291.59,354.37,104,False,400
4,B01DJLKZBA,Winfield 2 Hardside Expandable Luggage with Sp...,https://m.media-amazon.com/images/I/61NJoaZcP9...,https://www.amazon.com/dp/B01DJLKZBA,4.5,0,174.99,309.99,104,False,400
5,B07XSCD2R4,Maxlite 5 Softside Expandable Luggage with 4 S...,https://m.media-amazon.com/images/I/61LnBNsSBS...,https://www.amazon.com/dp/B07XSCD2R4,4.5,0,144.49,0.00,104,False,500
6,B07MXF4G8K,"Hard Shell Carry on Luggage Airline Approved, ...",https://m.media-amazon.com/images/I/71CghLYrnA...,https://www.amazon.com/dp/B07MXF4G8K,4.5,0,169.99,0.00,104,False,400
7,B07H515VCZ,"Maxporter II 30"" Hardside Spinner Trunk Luggag...",https://m.media-amazon.com/images/I/81f3h+YHOX...,https://www.amazon.com/dp/B07H515VCZ,4.5,0,299.99,0.00,104,False,100
8,B08BXBCNMQ,Omni 2 Hardside Expandable Luggage with Spinne...,https://m.media-amazon.com/images/I/91eOWP4myS...,https://www.amazon.com/dp/B08BXBCNMQ,4.5,0,112.63,137.04,104,False,500
9,B0B9K44XTS,Luggage Sets Expandable Lightweight Suitcases ...,https://m.media-amazon.com/images/I/81dsv5GrCL...,https://www.amazon.com/dp/B0B9K44XTS,4.4,0,209.99,0.00,104,False,200
10,B07QZLHTTY,Crew Versapack Softside Expandable 8 Spinner W...,https://m.media-amazon.com/images/I/71py6bRiEw...,https://www.amazon.com/dp/B07QZLHTTY,4.7,0,271.99,319.99,104,False,100
11,B01HIATG6I,Chatelet Hard+ Hardside Luggage with Spinner W...,https://m.media-amazon.com/images/I/81W+B3pWiQ...,https://www.amazon.com/dp/B01HIATG6I,4.6,0,259.60,413.33,104,False,100
12,B07QXD3J9G,Crew Versapack Softside Expandable 8 Spinner W...,https://m.media-amazon.com/images/I/71tFi58LKw...,https://www.amazon.com/dp/B07QXD3J9G,4.5,0,323.99,0.00,104,False,100
13,B081JDHNX1,Centric 2 Hardside Expandable Luggage with Spi...,https://m.media-amazon.com/images/I/81UXQZdNZz...,https://www.amazon.com/dp/B081JDHNX1,4.5,0,399.92,699.97,104,False,100
14,B07DMBG7CX,Xpedition 30 Inch Multi-Pocket Upright Rolling...,https://m.media-amazon.com/images/I/81QKjgbsq4...,https://www.amazon.com/dp/B07DMBG7CX,4.3,0,42.00,0.00,104,False,300
15,B0B2X1BDFH,Stratum 2.0 Expandable Hardside Luggage with S...,https://m.media-amazon.com/images/I/91qkFv-txy...,https://www.amazon.com/dp/B0B2X1BDFH,4.5,0,89.95,139.99,104,False,300
16,B00GI3572E,"Women's Spinner Mobile Office, Black, One Size",https://m.media-amazon.com/images/I/91qdE638dx...,https://www.amazon.com/dp/B00GI3572E,4.6,0,164.99,174.99,104,False,200
17,B084P184MG,Ascella X Softside Expandable Luggage with Spi...,https://m.media-amazon.com/images/I/910PxQKATh...,https://www.amazon.com/dp/B084P184MG,4.5,0,198.41,209.99,104,False,100
18,B094LVRCZD,Boren Polycarbonate Hardside Rugged Travel Sui...,https://m.media-amazon.com/images/I/611EC7sEWM...,https://www.amazon.com/dp/B094LVRCZD,3.9,0,99.99,0.00,104,False,300
19,B072Z7K96L,Clear PVC Suitcase Cover Protectors 28 Inch Lu...,https://m.media-amazon.com/images/I/71TXWZwZ1+...,https://www.amazon.com/dp/B072Z7K96L,4.2,0,17.99,19.99,104,False,1000

In [3]:
df.fillna(' ' , inplace=True)

In [4]:
df.drop(columns=['imgUrl'])

,asin,title,productURL,stars,reviews,price,listPrice,category_id,isBestSeller,boughtInLastMonth
0,B014TMV5YE,"Sion Softside Expandable Roller Luggage, Black...",https://www.amazon.com/dp/B014TMV5YE,4.5,0,139.99,0.00,104,False,2000
1,B07GDLCQXV,Luggage Sets Expandable PC+ABS Durable Suitcas...,https://www.amazon.com/dp/B07GDLCQXV,4.5,0,169.99,209.99,104,False,1000
2,B07XSCCZYG,Platinum Elite Softside Expandable Checked Lug...,https://www.amazon.com/dp/B07XSCCZYG,4.6,0,365.49,429.99,104,False,300
3,B08MVFKGJM,Freeform Hardside Expandable with Double Spinn...,https://www.amazon.com/dp/B08MVFKGJM,4.6,0,291.59,354.37,104,False,400
4,B01DJLKZBA,Winfield 2 Hardside Expandable Luggage with Sp...,https://www.amazon.com/dp/B01DJLKZBA,4.5,0,174.99,309.99,104,False,400
...,...,...,...,...,...,...,...,...,...,...
1426332,B00R3LIKCO,American Flag Patriotic USA Classic 5 Panel Me...,https://www.amazon.com/dp/B00R3LIKCO,4.2,0,14.95,0.00,112,False,0
1426333,B098BQ7ZQ3,Men's Baseball Cap - H2O-DRI Line Up Curved Br...,https://www.amazon.com/dp/B098BQ7ZQ3,4.4,0,33.99,0.00,112,False,0
1426334,B07X1MVNT1,[4 Pack] Adjustable Eyeglasses and Sunglasses ...,https://www.amazon.com/dp/B07X1MVNT1,3.6,0,8.54,0.00,112,False,0
1426335,B08XLBG8V9,Ax2002 Aviator Sunglasses,https://www.amazon.com/dp/B08XLBG8V9,4.5,0,54.36,57.39,112,False,0
1426336,B07GH67QC8,in Hoc Signo Vinces Knights Templar Masonic Em...,https://www.amazon.com/dp/B07GH67QC8,4.9,0,18.79,0.00,112,False,0