In [1]:
import pandas as pd
import numpy as np

In [2]:

data =pd.read_csv('/Users/mac/Documents/Chat-Bot-Telegram/DataSet/Kala/digikala-products.csv')
comment = pd.read_csv("/Users/mac/Documents/Chat-Bot-Telegram/DataSet/Kala/digikala-comments.csv")
data.head(2)

/var/folders/xn/9k_t21cj50q15j6t2z07zt640000gn/T/ipykernel_922/2269391988.py:1: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  data =pd.read_csv('/Users/mac/Documents/Chat-Bot-Telegram/DataSet/Kala/digikala-products.csv')

,id,title_fa,Rate,Rate_cnt,Category1,Category2,Brand,Price,Seller,Is_Fake,min_price_last_month,sub_category
0,7096438,آبسلانگ مدل s5 بسته 250 عددی,90,4,آبسلانگ,NaN,متفرقه,634800,سلامت ساز راد,False,0,beauty
1,2845119,آبسلانگ مدل M-1 بسته 400 عددی,84,217,آبسلانگ,NaN,متفرقه,818800,مهر افزون,False,0,beauty

In [3]:

data.fillna(' ' , inplace=True)
comment.fillna(' ' , inplace=True)
#data.head(1)
comment.head(20)

,id,title,body,created_at,rate,recommendation_status,is_buyer,product_id,advantages,disadvantages,likes,dislikes,seller_title,seller_code,true_to_size_rate
0,53672599,پیشنهاد نمیشود,به درد نمیخوره,23 شهریور 1402,1.0,not_recommended,True,252058,,,0,0,دیجی‌کالا,5A52N,
1,9897229,بسته بندی بد,می‌تونست به عنوان یه کالای فرهنگی بهتر بسته بن...,16 تیر 1399,0.0,recommended,True,252058,['تجربه جالبی بود برام '],['بسته بندی جالبی نداشت'],1,0,دیجی‌کالا,5A52N,
2,38074516,برس ریمل,بسته بندیش خوب بود\r\n کاربرد و کیفیتشم خیلی خ...,26 مرداد 1401,0.0,recommended,True,3331597,,,0,0,آرالیا بیوتی,ADM47,
3,18628562,خوبه و خوشرنگ,به نظرم خوبه فقط یکم ظریفه. از رنگش خوشم اومد ...,28 اسفند 1399,0.0,recommended,True,3331329,,,0,0,اینجاست آ,9ZMCZ,
4,53301258,برس رنگ مو,معمولیه اگه واسه خونه رنگ کردن شخصی میخواین او...,12 شهریور 1402,3.0,recommended,True,3255700,,,0,0,گالری آرایشی به سیما,CDWHA,
5,53266157,خوبه,قبلا هم استفاده کردم اگه بلد باشین کار کردن با...,11 شهریور 1402,5.0,recommended,True,3305270,,,0,0,یانگوم,ERKSP,
6,46206235,بدک نیست,خوبه,8 اسفند 1401,2.0,,True,3480048,,,0,0,بازرگانی سوشیان,CKWY4,
7,40597171,پد شستشوی براش,خیلی به کارتون میاد قیمتشم مناسبه,24 مهر 1401,5.0,recommended,True,3480048,"['جنسش خوبه\r', 'خوش رنگه\r', 'کاربردیه\r', 'ق...",['نداره '],1,0,بازرگانی سوشیان,CKWY4,
8,46198656,لنز ناخون,دقیقا مطابق عکس بود,7 اسفند 1401,5.0,recommended,True,7626372,,,0,0,هستی نیل,E2C2D,
9,46901811,خوب,برا حالت دادن با اسپری یا پودر عالیه,20 اسفند 1401,5.0,recommended,True,821812,,,0,0,پنی شاپ,CN6G3,
10,20373536,,اندازش کوچیکه بدرد رنگ مو نمیخوره,14 اردیبهشت 1400,2.0,not_recommended,True,1064806,,,0,0,آرالیا بیوتی,ADM47,
11,40710017,عالی,مطابق توضیحات بود,26 مهر 1401,3.0,recommended,True,2727911,,,0,0,آرالیا بیوتی,ADM47,
12,53791544,,لب ھارو نرم میکنہ و قیمت مناسب,26 شهریور 1402,5.0,recommended,True,3899330,,,0,0,سپیدرو,5A6A6,
13,52495314,خوب,خوب بود بخرید قشنگه,18 مرداد 1402,5.0,recommended,True,7693180,,,0,0,یانگوم,ERKSP,
14,34036284,قلم ماسک صورت,سالم بود،شستنش راحته،واسه ماسک گذاشتن خیلی اید...,31 فروردین 1401,3.0,recommended,True,4275289,,,1,0,الماس تجارت پارس,5AJY7,
15,51783725,خیلی خوب بود,خیلی عالی بود ، کاربردیه ، دیگه لازم نیست جوشا...,27 تیر 1402,4.0,recommended,True,1893093,,,0,0,کارگذاری جنوب,5AK5K,
16,52776060,اصلا بدرد نمیخوره نخرید,بدرد نخور واقعی وقتی بدستم رسید برسش کج بود و ...,27 مرداد 1402,1.0,not_recommended,True,3258998,,,0,0,یانگوم,ERKSP,
17,52767482,برس ابرو,کمی گران اما با کیفیت,27 مرداد 1402,5.0,recommended,True,9557523,,,0,0,شوز انلاین,AKMEA,
18,48786928,,خوب,11 اردیبهشت 1402,1.0,recommended,True,2645301,,,0,0,اینجاست آ,9ZMCZ,fit
19,25530926,,کیفیت چاپ خوب بود. اما چسب ها فاسد بودند,28 شهریور 1400,2.0,no_idea,True,5762473,,,1,0,مربع مکعب,DEKDY,

In [4]:
data = data[data['Price'].notna()]
data['Price']

0           634800
1           818800
2           920000
3          1100000
4          1530000
            ...
1283491    2500000
1283492    2150000
1283493    2100000
1283494    2300000
1283495    2800000
Name: Price, Length: 1283496, dtype: int64

In [5]:
def clean_text(data,column):
    data[column] = data[column].astype(str).str.lower()
    
clean_text(data,'title_fa')      
clean_text(comment,'body')      
clean_text(comment,'title')

In [11]:
data['text'] = " title product : "+ data['title_fa'] + ' Category1 ' + data['Category1'] + ' Category2 ' + data['Category2'] 

merge = pd.merge(data,comment,left_on='id',right_on='product_id',how='left')

merge['comment_text'] = (
    'id:' + merge['product_id'].astype(str) +
    'title : ' + merge['title'] +
    ' body : ' + merge['body'] +
    'rating :' + merge['rate'].astype(str)
)
#data['comment'] = merge['comment_text']

grouped_comment = merge.groupby('product_id')['comment_text'].apply(lambda x: " ".join(x)).reset_index()

data = pd.merge(data,grouped_comment, left_on='id' , right_on='product_id')

data.drop(columns='product_id',inplace=True)

data.fillna(' ' , inplace=True)


data.head(50)

,id,title_fa,Rate,Rate_cnt,Category1,Category2,Brand,Price,Seller,Is_Fake,min_price_last_month,sub_category,text,comment_text
0,7096438,آبسلانگ مدل s5 بسته 250 عددی,90,4,آبسلانگ,,متفرقه,634800,سلامت ساز راد,False,0,beauty,title product : آبسلانگ مدل s5 بسته 250 عددی ...,id:7096438.0title : body : عالیه عالیه صیقلی...
1,2845119,آبسلانگ مدل m-1 بسته 400 عددی,84,217,آبسلانگ,,متفرقه,818800,مهر افزون,False,0,beauty,title product : آبسلانگ مدل m-1 بسته 400 عدد...,id:2845119.0title : body : عالیrating :5.0 i...
2,6117745,آبسلانگ مدل m50 مجموعه 500 عددی,88,14,آبسلانگ,,متفرقه,920000,یانگوم,False,0,beauty,title product : آبسلانگ مدل m50 مجموعه 500 عد...,id:6117745.0title : body : من راضی ام.بعضی ه...
3,1912926,استند ابسلانگ مدل s01,78,25,آبسلانگ,,متفرقه,1100000,بهراد طب بیدار,False,0,beauty,title product : استند ابسلانگ مدل s01 Categor...,id:1912926.0title : کیفیت پایین body : اصلا خو...
4,6335462,آبسلانگ نوری تسلامد مدل all-in-one,84,25,آبسلانگ,,تسلا مد,1530000,دیجی‌کالا,False,0,beauty,title product : آبسلانگ نوری تسلامد مدل all-i...,id:6335462.0title : body : در مطب برای بچه ...
5,6335562,سری آبسلانگ تسلامد مدل all-in-one بسته 100 عددی,80,6,آبسلانگ,,تسلا مد,1521000,دیجی‌کالا,False,0,beauty,title product : سری آبسلانگ تسلامد مدل all-in...,id:6335562.0title : body : برای آبسلانگ نوری...
6,7096725,آبسلانگ مدل s20 بسته 1000 عددی,84,6,آبسلانگ,,متفرقه,1889500,سلامت ساز راد,False,0,beauty,title product : آبسلانگ مدل s20 بسته 1000 عدد...,id:7096725.0title : body : جنس خوب rating :4...
7,6005981,استند آبسلانگ گلدن بیوتی مدل 01,84,5,آبسلانگ,,متفرقه,1940000,گلد بیوتی سنتر,False,0,beauty,title product : استند آبسلانگ گلدن بیوتی مدل ...,id:6005981.0title : خوب body : سلام \n\nخوب بو...
8,4077287,آبسلانگ پل ایده آل پارس مدل td بسته 150 عددی,90,15,آبسلانگ,,پل ایده آل پارس,2150000,یاساطب,False,0,beauty,title product : آبسلانگ پل ایده آل پارس مدل t...,id:4077287.0title : عالی body : محمو تر از چوب...
9,10179102,آبسلانگ مدل a1 بسته 30 عددی,80,29,آبسلانگ,,متفرقه,90000,کانون طب نوین,False,0,beauty,title product : آبسلانگ مدل a1 بسته 30 عددی C...,id:10179102.0title : body : خوبه بدک نیستrat...
10,1743408,آبسلانگ مدل 1006 مجموعه 10 عددی,68,7,آبسلانگ,,متفرقه,125000,یانگوم,False,0,beauty,title product : آبسلانگ مدل 1006 مجموعه 10 عد...,id:1743408.0title : body : بد نیست ....ratin...
11,3901016,آبسلانگ مدل 01 بسته 50 عددی,78,9,آبسلانگ,,متفرقه,205700,سلامت ساز راد,False,0,beauty,title product : آبسلانگ مدل 01 بسته 50 عددی C...,id:3901016.0title : آبسلانگ body : دوتا بسته 2...
12,8950128,آبسلانگ مدل چوبی بسته 30 عددی,40,2,آبسلانگ,,متفرقه,199000,تجهیزات پزشکی بهنام,False,0,beauty,title product : آبسلانگ مدل چوبی بسته 30 عددی...,id:8950128.0title : قیمت ۱۲ برابری body : آبسل...
13,872243,آبسلانگ مدل 001 بسته 50 عددی,68,49,آبسلانگ,,متفرقه,195000,دریادشت,False,0,beauty,title product : آبسلانگ مدل 001 بسته 50 عددی ...,id:872243.0title : خوب و باکیفیت body : خوب و ...
14,9861719,آبسلانگ مدل 01 بسته 30 عددی,80,19,آبسلانگ,,متفرقه,209300,دریادشت,False,0,beauty,title product : آبسلانگ مدل 01 بسته 30 عددی C...,id:9861719.0title : خیلی خوب body : کیفیت متوس...
15,8377402,آبسلانگ مدل s1 بسته 40 عددی,74,15,آبسلانگ,,متفرقه,137000,یانگوم,False,0,beauty,title product : آبسلانگ مدل s1 بسته 40 عددی C...,id:8377402.0title : body : پوسته پوسته شده ب...
16,3790239,آبسلانگ مدل m-1 بسته 35 عددی کالا,78,29,آبسلانگ,,متفرقه,214000,یانگوم,True,0,beauty,title product : آبسلانگ مدل m-1 بسته 35 عددی ...,id:3790239.0title : ابسلانگ body : دی جی نوشته...
17,6753033,آبسلانگ مدل t5 بسته 150 عددی,82,20,آبسلانگ,,متفرقه,340800,سلامت ساز راد,False,0,beauty,title product : آبسلانگ مدل t5 بسته 150 عددی ...,id:6753033.0title : body : قیمتش خوبه بدرد ب...
18,6517362,آبسلانگ ارتوطب مدل a40 بسته 40 عددی,74,14,آبسلانگ,,متفرقه,280000,آرام طب,False,0,beauty,title product : آبسلانگ ارتوطب مدل a40 بسته 4...,id:6517362.0title : آشغال داخل جعبه body : کل...
19,2928512,آبسلانگ مدل m-1 بسته 80 عددی,82,361,آبسلانگ,,متفرقه,252900,سلامت ساز راد,False,0,beauty,title product : آبسلانگ مدل m-1 بسته 80 عددی ...,id:2928512.0title : body : بسته بندی خوب و م...
20,6075092,آبسلانگ مدل m01 بسته 50 عددی,66,4,آبسلانگ,,متفرقه,229000,یانگوم,False,0,beauty,title product : آبسلانگ مدل m01 بسته 50 عددی ...,id:6075092.0title : خوب بود body : یکم از تعدا...
21,6554336,آبسلانگ مدل 05 بسته 120 عددی,82,18,آبسلانگ,,متفرقه,364400,پخش پرواز,False,0,beauty,title product : آبسلانگ مدل 05 بسته 120 عددی ...,id:6554336.0title : body : خوب بودrating :5....
22,11051125,آبسلانگ مدل hdr بسته 30 عددی,100,1,آبسلانگ,,متفرقه,251000,یانگوم,False,0,beauty,title product : آبسلانگ مدل hdr بسته 30 عددی ...,id:11051125.0title : body : عالیrating :5.0
23,9855257,آبسلانگ مدل آلار بسته 40 عددی,0,0,آبسلانگ,,متفرقه,284000,یانگوم,False,0,beauty,title product : آبسلانگ مدل آلار بسته 40 عددی...,id:9855257.0title : body : این آبسلانگ بنظرم...
24,1452939,آبسلانگ مدل 1002 بسته 30 عددی,76,166,آبسلانگ,,متفرقه,245000,سلامت ساز راد,False,0,beauty,title product : آبسلانگ مدل 1002 بسته 30 عددی...,id:1452939.0title : body : بسیار خوب و کاربر...
25,1452939,آبسلانگ مدل 1002 بسته 30 عددی,76,166,آبسلانگ,,متفرقه,245000,سلامت ساز راد,False,0,beauty,title product : آبسلانگ مدل 1002 بسته 30 عددی...,id:1452939.0title : body : بسیار خوب و کاربر...
26,8033206,آبسلانگ مدل rsh0200 بسته 200 عددی,86,94,آبسلانگ,,متفرقه,430000,آرام طب,False,0,beauty,title product : آبسلانگ مدل rsh0200 بسته 200 ...,id:8033206.0title : body : من برای اپیلاسیون...
27,10392313,آبسلانگ مدل b10 بسته 300 عددی,74,7,آبسلانگ,,متفرقه,611500,سلامت ساز راد,False,0,beauty,title product : آبسلانگ مدل b10 بسته 300 عددی...,id:10392313.0title : body : عالیrating :4.0 ...
28,8462605,آبسلانگ مدل bx بسته 2500 عددی,70,2,آبسلانگ,,متفرقه,5200000,مهر افزون,False,0,beauty,title product : آبسلانگ مدل bx بسته 2500 عددی...,id:8462605.0title : body : عالیrating :5.0
29,3474676,ژل ابرو استفانی مدل s1,78,62,آرایش ابرو,ژل و صابون ابرو,متفرقه,912000,سالسابیوتی,False,0,beauty,title product : ژل ابرو استفانی مدل s1 Catego...,id:3474676.0title : body : کیفیت خوبی نداشت ...
30,12114752,صابون ابرو دیفکتو مدل آرگان,80,10,آرایش ابرو,ژل و صابون ابرو,دیفکتو,930000,آلارز کازمتیک,False,0,beauty,title product : صابون ابرو دیفکتو مدل آرگان C...,id:12114752.0title : body : عالی بودrating :...
31,6801218,صابون لیفت ابرو ژیوار مدل b141 به همراه برس ابرو,84,53,آرایش ابرو,ژل و صابون ابرو,متفرقه,935000,کوتکا,False,0,beauty,title product : صابون لیفت ابرو ژیوار مدل b14...,id:6801218.0title : جنسش بد بود به یکماه نرسید...
32,2197343,ریمل ابرو آدور کوین شماره r06,78,113,آرایش ابرو,ریمل ابرو,آدور کوین,930000,زیباوش,False,930000,beauty,title product : ریمل ابرو آدور کوین شماره r06...,id:2197343.0title : body : رنگش تیره هستrati...
33,9884368,صابون لیفت ابرو بل کد 02,0,0,آرایش ابرو,ژل و صابون ابرو,بل,950000,کیلش,False,0,beauty,title product : صابون لیفت ابرو بل کد 02 Cate...,id:9884368.0title : خوب body : خوبrating :5.0
34,10075732,مداد ابرو لچیک مدل چوبی شماره 302,100,2,آرایش ابرو,مداد ابرو,لچیک,964100,پاریس بیوتی,False,0,beauty,title product : مداد ابرو لچیک مدل چوبی شماره...,id:10075732.0title : body : یعنی شک نکنید تو...
35,1051770,مداد ابرو گلدن رز مدل dream شماره 305,84,59,آرایش ابرو,مداد ابرو,گلدن رز,950000,زیباوش,False,0,beauty,title product : مداد ابرو گلدن رز مدل dream ش...,id:1051770.0title : body : خیلی نرم و خوشرنگ...
36,10076032,مداد ابرو لچیک مدل چوبی برس دار شماره 305,78,7,آرایش ابرو,مداد ابرو,لچیک,950000,مون لایت بیوتی,False,0,beauty,title product : مداد ابرو لچیک مدل چوبی برس د...,id:10076032.0title : body : چرب و شکننده - ق...
37,10076053,مداد ابرو لچیک مدل چوبی شماره 306,60,5,آرایش ابرو,مداد ابرو,لچیک,976900,پاریس بیوتی,False,0,beauty,title product : مداد ابرو لچیک مدل چوبی شماره...,id:10076053.0title : خوب body : خوب استrating ...
38,10076012,مداد ابرو لچیک مدل چوبی شماره 304,74,3,آرایش ابرو,مداد ابرو,لچیک,988200,پاریس بیوتی,False,0,beauty,title product : مداد ابرو لچیک مدل چوبی شماره...,id:10076012.0title : مداد ابرو لچیک body : کیف...
39,2643229,مداد ابرو رویال اترنیتی شماره 600,100,2,آرایش ابرو,مداد ابرو,رویال اترنیتی,940000,پخش نیک آیین,False,940000,beauty,title product : مداد ابرو رویال اترنیتی شماره...,id:2643229.0title : خوب بود body : عالی بودrat...
40,1900208,ریمل ابرو دونادیا شماره 004,72,54,آرایش ابرو,ریمل ابرو,دونادیا,940000,ولنجک بیوتی,False,0,beauty,title product : ریمل ابرو دونادیا شماره 004 C...,id:1900208.0title : body : خوبهrating :3.0 i...
41,744541,مداد ابرو گرین فیس شماره 404,70,2,آرایش ابرو,مداد ابرو,گرین فیس,950000,امیر نشان,False,0,beauty,title product : مداد ابرو گرین فیس شماره 404 ...,id:744541.0title : کیفیت قابل قبول body : کیفی...
42,10433722,صابون لیفت ابرو رومئو مدل r01,82,11,آرایش ابرو,ژل و صابون ابرو,متفرقه,960000,گالری الین بیوتی,False,0,beauty,title product : صابون لیفت ابرو رومئو مدل r0...,id:10433722.0title : body : لیفت عالی داره و...
43,153006,مداد ابرو اتود مدل etude corporation شماره 35,78,534,آرایش ابرو,مداد ابرو,اتود,964500,پرشیاکالا,False,0,beauty,title product : مداد ابرو اتود مدل etude corp...,id:153006.0title : عالی body : عالیrating :5.0...
44,8629422,مداد ابرو الستر مدل ra21,80,1,آرایش ابرو,مداد ابرو,الستر,966000,گدیر,False,0,beauty,title product : مداد ابرو الستر مدل ra21 Cate...,id:8629422.0title : مدادابرو body : خیلی خیلی ...
45,9401718,ژل ابرو کالیستا مدل shapestyle,66,19,آرایش ابرو,ژل و صابون ابرو,کالیستا,987900,لاکی بیوتی,False,0,beauty,title product : ژل ابرو کالیستا مدل shapestyl...,id:9401718.0title : body : حجمش کم هست ،موها...
46,10075670,مداد ابرو لچیک مدل چوبی شماره 300,88,22,آرایش ابرو,مداد ابرو,لچیک,1000000,پاریس بیوتی,False,0,beauty,title product : مداد ابرو لچیک مدل چوبی شماره...,id:10075670.0title : مداد چشم body : کاملا فیک...
47,2197341,ریمل ابرو آدور کوین شماره r04,78,136,آرایش ابرو,ریمل ابرو,آدور کوین,989500,باباریا,False,939400,beauty,title product : ریمل ابرو آدور کوین شماره r04...,id:2197341.0title : خوبه body : در کل خوبهrati...
48,8805609,ژل نقویت کننده مژه و ابرو بارین بیوتی شماره 6 ...,80,5,آرایش ابرو,تقویت‌کننده ابرو,متفرقه,983200,باباریا,False,851000,beauty,title product : ژل نقویت کننده مژه و ابرو بار...,id:8805609.0title : ژل تقویت کننده مژه ابرو bo...
49,1502674,سایه ابرو گلدن رز شماره103,74,30,آرایش ابرو,سایه ابرو,گلدن رز,1560000,زیباوش,False,0,beauty,title product : سایه ابرو گلدن رز شماره103 Ca...,id:1502674.0title : body : عالی بودن وبا کیف...

In [12]:
merge.to_csv('kala.csv')