In [5]:
import pandas as pd
import numpy as np

In [6]:

data =pd.read_csv('/Users/mac/Documents/Chat-Bot-Telegram/DataSet/Kala/digikala-products.csv')
comment = pd.read_csv("/Users/mac/Documents/Chat-Bot-Telegram/DataSet/Kala/digikala-comments.csv")
comment.head(2)

/var/folders/xn/9k_t21cj50q15j6t2z07zt640000gn/T/ipykernel_2489/268026212.py:1: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  data =pd.read_csv('/Users/mac/Documents/Chat-Bot-Telegram/DataSet/Kala/digikala-products.csv')

,id,title,body,created_at,rate,recommendation_status,is_buyer,product_id,advantages,disadvantages,likes,dislikes,seller_title,seller_code,true_to_size_rate
0,53672599,پیشنهاد نمیشود,به درد نمیخوره,23 شهریور 1402,1.0,not_recommended,True,252058,NaN,NaN,0,0,دیجی‌کالا,5A52N,NaN
1,9897229,بسته بندی بد,می‌تونست به عنوان یه کالای فرهنگی بهتر بسته بن...,16 تیر 1399,0.0,recommended,True,252058,['تجربه جالبی بود برام '],['بسته بندی جالبی نداشت'],1,0,دیجی‌کالا,5A52N,NaN

In [7]:
data.fillna(' ' , inplace=True)
comment.fillna(' ' , inplace=True)
data.head(1)

,id,title_fa,Rate,Rate_cnt,Category1,Category2,Brand,Price,Seller,Is_Fake,min_price_last_month,sub_category
0,7096438,آبسلانگ مدل s5 بسته 250 عددی,90,4,آبسلانگ,,متفرقه,634800,سلامت ساز راد,False,0,beauty

In [4]:
data = data[data['Price'].notna()]
data['Price']

0           634800
1           818800
2           920000
3          1100000
4          1530000
            ...
1283491    2500000
1283492    2150000
1283493    2100000
1283494    2300000
1283495    2800000
Name: Price, Length: 1283496, dtype: int64

In [5]:
def clean_text(data,column):
    data[column] = data[column].astype(str).str.lower()
data[''] = clean_text(data,'title_fa')

In [6]:
data['text'] = data['title_fa'] + ' ' + data['Category1'] + ' ' + data['Category2']
data.head(20)

,id,title_fa,Rate,Rate_cnt,Category1,Category2,Brand,Price,Seller,Is_Fake,min_price_last_month,sub_category,,text
0,7096438,آبسلانگ مدل s5 بسته 250 عددی,90,4,آبسلانگ,,متفرقه,634800,سلامت ساز راد,False,0,beauty,None,آبسلانگ مدل s5 بسته 250 عددی آبسلانگ
1,2845119,آبسلانگ مدل m-1 بسته 400 عددی,84,217,آبسلانگ,,متفرقه,818800,مهر افزون,False,0,beauty,None,آبسلانگ مدل m-1 بسته 400 عددی آبسلانگ
2,6117745,آبسلانگ مدل m50 مجموعه 500 عددی,88,14,آبسلانگ,,متفرقه,920000,یانگوم,False,0,beauty,None,آبسلانگ مدل m50 مجموعه 500 عددی آبسلانگ
3,1912926,استند ابسلانگ مدل s01,78,25,آبسلانگ,,متفرقه,1100000,بهراد طب بیدار,False,0,beauty,None,استند ابسلانگ مدل s01 آبسلانگ
4,6335462,آبسلانگ نوری تسلامد مدل all-in-one,84,25,آبسلانگ,,تسلا مد,1530000,دیجی‌کالا,False,0,beauty,None,آبسلانگ نوری تسلامد مدل all-in-one آبسلانگ
5,6335562,سری آبسلانگ تسلامد مدل all-in-one بسته 100 عددی,80,6,آبسلانگ,,تسلا مد,1521000,دیجی‌کالا,False,0,beauty,None,سری آبسلانگ تسلامد مدل all-in-one بسته 100 عدد...
6,7096725,آبسلانگ مدل s20 بسته 1000 عددی,84,6,آبسلانگ,,متفرقه,1889500,سلامت ساز راد,False,0,beauty,None,آبسلانگ مدل s20 بسته 1000 عددی آبسلانگ
7,7096768,آبسلانگ مدل s10 بسته 500 عددی,100,2,آبسلانگ,,متفرقه,1872000,سلامت ساز راد,False,0,beauty,None,آبسلانگ مدل s10 بسته 500 عددی آبسلانگ
8,6005981,استند آبسلانگ گلدن بیوتی مدل 01,84,5,آبسلانگ,,متفرقه,1940000,گلد بیوتی سنتر,False,0,beauty,None,استند آبسلانگ گلدن بیوتی مدل 01 آبسلانگ
9,4077287,آبسلانگ پل ایده آل پارس مدل td بسته 150 عددی,90,15,آبسلانگ,,پل ایده آل پارس,2150000,یاساطب,False,0,beauty,None,آبسلانگ پل ایده آل پارس مدل td بسته 150 عددی ...
10,10179102,آبسلانگ مدل a1 بسته 30 عددی,80,29,آبسلانگ,,متفرقه,90000,کانون طب نوین,False,0,beauty,None,آبسلانگ مدل a1 بسته 30 عددی آبسلانگ
11,1743408,آبسلانگ مدل 1006 مجموعه 10 عددی,68,7,آبسلانگ,,متفرقه,125000,یانگوم,False,0,beauty,None,آبسلانگ مدل 1006 مجموعه 10 عددی آبسلانگ
12,3901016,آبسلانگ مدل 01 بسته 50 عددی,78,9,آبسلانگ,,متفرقه,205700,سلامت ساز راد,False,0,beauty,None,آبسلانگ مدل 01 بسته 50 عددی آبسلانگ
13,8950128,آبسلانگ مدل چوبی بسته 30 عددی,40,2,آبسلانگ,,متفرقه,199000,تجهیزات پزشکی بهنام,False,0,beauty,None,آبسلانگ مدل چوبی بسته 30 عددی آبسلانگ
14,872243,آبسلانگ مدل 001 بسته 50 عددی,68,49,آبسلانگ,,متفرقه,195000,دریادشت,False,0,beauty,None,آبسلانگ مدل 001 بسته 50 عددی آبسلانگ
15,9861719,آبسلانگ مدل 01 بسته 30 عددی,80,19,آبسلانگ,,متفرقه,209300,دریادشت,False,0,beauty,None,آبسلانگ مدل 01 بسته 30 عددی آبسلانگ
16,8377402,آبسلانگ مدل s1 بسته 40 عددی,74,15,آبسلانگ,,متفرقه,137000,یانگوم,False,0,beauty,None,آبسلانگ مدل s1 بسته 40 عددی آبسلانگ
17,3790239,آبسلانگ مدل m-1 بسته 35 عددی کالا,78,29,آبسلانگ,,متفرقه,214000,یانگوم,True,0,beauty,None,آبسلانگ مدل m-1 بسته 35 عددی کالا آبسلانگ
18,6753033,آبسلانگ مدل t5 بسته 150 عددی,82,20,آبسلانگ,,متفرقه,340800,سلامت ساز راد,False,0,beauty,None,آبسلانگ مدل t5 بسته 150 عددی آبسلانگ
19,6517362,آبسلانگ ارتوطب مدل a40 بسته 40 عددی,74,14,آبسلانگ,,متفرقه,280000,آرام طب,False,0,beauty,None,آبسلانگ ارتوطب مدل a40 بسته 40 عددی آبسلانگ

In [9]:
data.to_csv('kala.csv')