In [3]:
import pandas as pd
import numpy as np

In [4]:

data =pd.read_csv('/Users/mac/Documents/Chat-Bot-Telegram/DataSet/Kala/digikala-products.csv')
comment = pd.read_csv("/Users/mac/Documents/Chat-Bot-Telegram/DataSet/Kala/digikala-comments.csv")
data.head(2)

/var/folders/xn/9k_t21cj50q15j6t2z07zt640000gn/T/ipykernel_905/2269391988.py:1: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  data =pd.read_csv('/Users/mac/Documents/Chat-Bot-Telegram/DataSet/Kala/digikala-products.csv')

,id,title_fa,Rate,Rate_cnt,Category1,Category2,Brand,Price,Seller,Is_Fake,min_price_last_month,sub_category
0,7096438,آبسلانگ مدل s5 بسته 250 عددی,90,4,آبسلانگ,NaN,متفرقه,634800,سلامت ساز راد,False,0,beauty
1,2845119,آبسلانگ مدل M-1 بسته 400 عددی,84,217,آبسلانگ,NaN,متفرقه,818800,مهر افزون,False,0,beauty

In [5]:

data.fillna(' ' , inplace=True)
comment.fillna(' ' , inplace=True)
#data.head(1)
comment.head(20)

,id,title,body,created_at,rate,recommendation_status,is_buyer,product_id,advantages,disadvantages,likes,dislikes,seller_title,seller_code,true_to_size_rate
0,53672599,پیشنهاد نمیشود,به درد نمیخوره,23 شهریور 1402,1.0,not_recommended,True,252058,,,0,0,دیجی‌کالا,5A52N,
1,9897229,بسته بندی بد,می‌تونست به عنوان یه کالای فرهنگی بهتر بسته بن...,16 تیر 1399,0.0,recommended,True,252058,['تجربه جالبی بود برام '],['بسته بندی جالبی نداشت'],1,0,دیجی‌کالا,5A52N,
2,38074516,برس ریمل,بسته بندیش خوب بود\r\n کاربرد و کیفیتشم خیلی خ...,26 مرداد 1401,0.0,recommended,True,3331597,,,0,0,آرالیا بیوتی,ADM47,
3,18628562,خوبه و خوشرنگ,به نظرم خوبه فقط یکم ظریفه. از رنگش خوشم اومد ...,28 اسفند 1399,0.0,recommended,True,3331329,,,0,0,اینجاست آ,9ZMCZ,
4,53301258,برس رنگ مو,معمولیه اگه واسه خونه رنگ کردن شخصی میخواین او...,12 شهریور 1402,3.0,recommended,True,3255700,,,0,0,گالری آرایشی به سیما,CDWHA,
5,53266157,خوبه,قبلا هم استفاده کردم اگه بلد باشین کار کردن با...,11 شهریور 1402,5.0,recommended,True,3305270,,,0,0,یانگوم,ERKSP,
6,46206235,بدک نیست,خوبه,8 اسفند 1401,2.0,,True,3480048,,,0,0,بازرگانی سوشیان,CKWY4,
7,40597171,پد شستشوی براش,خیلی به کارتون میاد قیمتشم مناسبه,24 مهر 1401,5.0,recommended,True,3480048,"['جنسش خوبه\r', 'خوش رنگه\r', 'کاربردیه\r', 'ق...",['نداره '],1,0,بازرگانی سوشیان,CKWY4,
8,46198656,لنز ناخون,دقیقا مطابق عکس بود,7 اسفند 1401,5.0,recommended,True,7626372,,,0,0,هستی نیل,E2C2D,
9,46901811,خوب,برا حالت دادن با اسپری یا پودر عالیه,20 اسفند 1401,5.0,recommended,True,821812,,,0,0,پنی شاپ,CN6G3,
10,20373536,,اندازش کوچیکه بدرد رنگ مو نمیخوره,14 اردیبهشت 1400,2.0,not_recommended,True,1064806,,,0,0,آرالیا بیوتی,ADM47,
11,40710017,عالی,مطابق توضیحات بود,26 مهر 1401,3.0,recommended,True,2727911,,,0,0,آرالیا بیوتی,ADM47,
12,53791544,,لب ھارو نرم میکنہ و قیمت مناسب,26 شهریور 1402,5.0,recommended,True,3899330,,,0,0,سپیدرو,5A6A6,
13,52495314,خوب,خوب بود بخرید قشنگه,18 مرداد 1402,5.0,recommended,True,7693180,,,0,0,یانگوم,ERKSP,
14,34036284,قلم ماسک صورت,سالم بود،شستنش راحته،واسه ماسک گذاشتن خیلی اید...,31 فروردین 1401,3.0,recommended,True,4275289,,,1,0,الماس تجارت پارس,5AJY7,
15,51783725,خیلی خوب بود,خیلی عالی بود ، کاربردیه ، دیگه لازم نیست جوشا...,27 تیر 1402,4.0,recommended,True,1893093,,,0,0,کارگذاری جنوب,5AK5K,
16,52776060,اصلا بدرد نمیخوره نخرید,بدرد نخور واقعی وقتی بدستم رسید برسش کج بود و ...,27 مرداد 1402,1.0,not_recommended,True,3258998,,,0,0,یانگوم,ERKSP,
17,52767482,برس ابرو,کمی گران اما با کیفیت,27 مرداد 1402,5.0,recommended,True,9557523,,,0,0,شوز انلاین,AKMEA,
18,48786928,,خوب,11 اردیبهشت 1402,1.0,recommended,True,2645301,,,0,0,اینجاست آ,9ZMCZ,fit
19,25530926,,کیفیت چاپ خوب بود. اما چسب ها فاسد بودند,28 شهریور 1400,2.0,no_idea,True,5762473,,,1,0,مربع مکعب,DEKDY,

In [6]:
data = data[data['Price'].notna()]
data['Price']

0           634800
1           818800
2           920000
3          1100000
4          1530000
            ...
1283491    2500000
1283492    2150000
1283493    2100000
1283494    2300000
1283495    2800000
Name: Price, Length: 1283496, dtype: int64

In [7]:
def clean_text(data,column):
    data[column] = data[column].astype(str).str.lower()
    
clean_text(data,'title_fa')      
clean_text(comment,'body')      
clean_text(comment,'title')

In [ ]:
data['text'] = " title product : "+ data['title_fa'] + ' Category1 ' + data['Category1'] + ' Category2 ' + data['Category2'] 

merge = pd.merge(data,comment,left_on='id',right_on='product_id',how='left')
merge['comment_text'] = 'id:' + merge['product_id'] + 'title : ' + merge['title'] + ' body : ' + merge['body'] + 'rating :' + merge['rate']

data.fillna(' ' , inplace=True)

data.head(50)

In [9]:
data.to_csv('kala.csv')