In [51]:
import pandas as pd
import numpy as np
import math

In [52]:

data =pd.read_csv('/Users/mac/Documents/Chat-Bot-Telegram/DataSet/Kala/digikala-products.csv')

data.head(2)

/var/folders/xn/9k_t21cj50q15j6t2z07zt640000gn/T/ipykernel_966/2626237418.py:1: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  data =pd.read_csv('/Users/mac/Documents/Chat-Bot-Telegram/DataSet/Kala/digikala-products.csv')

,id,title_fa,Rate,Rate_cnt,Category1,Category2,Brand,Price,Seller,Is_Fake,min_price_last_month,sub_category
0,7096438,آبسلانگ مدل s5 بسته 250 عددی,90,4,آبسلانگ,NaN,متفرقه,634800,سلامت ساز راد,False,0,beauty
1,2845119,آبسلانگ مدل M-1 بسته 400 عددی,84,217,آبسلانگ,NaN,متفرقه,818800,مهر افزون,False,0,beauty

In [ ]:
data.fillna(' ' , inplace=True)
data.head(100)

,id,title_fa,Rate,Rate_cnt,Category1,Category2,Brand,Price,Seller,Is_Fake,min_price_last_month,sub_category
0,7096438,آبسلانگ مدل s5 بسته 250 عددی,90,4,آبسلانگ,,متفرقه,634800,سلامت ساز راد,False,0,beauty
1,2845119,آبسلانگ مدل M-1 بسته 400 عددی,84,217,آبسلانگ,,متفرقه,818800,مهر افزون,False,0,beauty
2,6117745,آبسلانگ مدل m50 مجموعه 500 عددی,88,14,آبسلانگ,,متفرقه,920000,یانگوم,False,0,beauty
3,1912926,استند ابسلانگ مدل S01,78,25,آبسلانگ,,متفرقه,1100000,بهراد طب بیدار,False,0,beauty
4,6335462,آبسلانگ نوری تسلامد مدل All-in-One,84,25,آبسلانگ,,تسلا مد,1530000,دیجی‌کالا,False,0,beauty
...,...,...,...,...,...,...,...,...,...,...,...,...
95,2367102,محلول تقویت کننده مژه و ابرو سسدرما مدل SESLAS...,76,90,آرایش ابرو,تقویت‌کننده ابرو,سسدرما,9400000,نوین تجارت رادناس,False,0,beauty
96,9732352,مداد ابرو آرکانسیل مدل Ideal شماره 200,80,1,آرایش ابرو,مداد ابرو,آرکانسیل,9700000,کیان بیوتی,False,0,beauty
97,1287142,پالت سایه ابرو استودیو میکاپ مدل Brow Sculptin...,0,0,آرایش ابرو,سایه ابرو,استودیو میکاپ,9620000,استودیو میکاپ ایران,False,0,beauty
98,1287141,سایه ابرو استودیو میکاپ مدل Brow Sculpting شما...,0,0,آرایش ابرو,سایه ابرو,استودیو میکاپ,9620000,استودیو میکاپ ایران,False,0,beauty
99,1983440,محلول احیا کننده ابرو سریتا مدل Eyebrow Vitali...,84,84,آرایش ابرو,تقویت‌کننده ابرو,سریتا,10700000,سریتا طب,False,9650000,beauty